version: '3.9'
services:
  app:
    container_name: blog_app
    build: .
    command: uvicorn src.router:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    container_name: blog_db
    image: mongo:4.4
    ports:
      - 27017:27017
    volumes:
      - db_data:/data/db

volumes:
  db_data:
